# Nome do Workflow
name: Frontend Pipeline - Hackathon

# Evento que irá acionar a pipeline
on: 
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download do Repositório
        uses: actions/checkout@v4       # https://github.com/actions/checkout
        with:
          fetch-depth: 0

      #- name: SonarCloud Scan
      #  uses: sonarsource/sonarcloud-github-action@master  # https://github.com/marketplace/actions/sonarcloud-scan
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  

      - name: Login Artifactory Registry
        uses: docker/login-action@v3  # https://github.com/marketplace/actions/docker-login
        with:
          registry: ${{ vars.GOOGLE_ARTIFACT }}
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build & Push Image
        run: | 
          docker build -t ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}-front:latest --build-arg BACKEND_URL=${{ secrets.BACKEND_URL }} .
          docker push ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}-front:latest

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Auth GCP
        uses: 'google-github-actions/auth@v1' # https://github.com/google-github-actions/auth
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Deploy Frontend - Cloud Run
        id: deploy-front
        run: |-
          gcloud run deploy frontend \
            --quiet \
            --region  ${{ vars.GOOGLE_REGION }} \
            --image ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}-front:latest \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ vars.GOOGLE_PROJECT_ID }} \
            --format json